global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'password-scorer-api'
    static_configs:
      - targets: 
        - 'api-1:8000'
        - 'api-2:8000' 
        - 'api-3:8000'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nginx-health'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/health'
    scrape_interval: 15s